version: "3"

services:
  server:
    image: itzg/minecraft-server:latest
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      ENABLE_RCON: "true"
      RCON_PASSWORD: "testing"
      RCON_PORT: 28016
      # enable env variable replacement
      REPLACE_ENV_VARIABLES: "TRUE"
      # define an optional prefix for your env variables you want to replace
      ENV_VARIABLE_PREFIX: "CFG_"
      # and here are the actual variables
      CFG_DB_HOST: "http://localhost:3306"
      CFG_DB_NAME: "minecraft"
      CFG_DB_PASSWORD_FILE: "/run/secrets/db_password"
      VERSION: '1.16.5'
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - ./data:/data
  bluemap:
    image: ghcr.io/bluemap-minecraft/bluemap:latest
    restart: unless-stopped
    command: -r -u -w
    ports:
      - '8100:8100'
    tty: true
    stdin_open: true
    volumes:
      - './bluemap/config:/app/config'
      - './data/world:/app/world'
      - './data/world_nether:/app/world_nether'
      - './data/world_the_end:/app/world_the_end'
      - './bluemap/data:/app/data'
      - './bluemap/web:/app/web'
