version: "3"

services:
  balancer:
    image: itzg/minecraft-server:latest
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
    networks:
      default:
        ipv4_address: 11.201.100.100
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 11.201.100.0/24
          gateway: 11.201.100.1