version: "3"

services:
  server:
    image: itzg/minecraft-server:latest
    environment:
      EULA: "TRUE"
    volumes:
      - ./data:/data
    networks:
      default:
        ipv4_address: 11.201.100.100

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 11.201.100.0/24
          gateway: 11.201.100.1